<?php $randomPlayerList = rand(0, 10000); ?>
<?php $randomPlugins = rand(0, 10000); ?>
<?php echo $args['before_widget']; ?>
<?php echo $args['before_title'] . $instance['title'] . $args['after_title']; ?>
<p>
    Status: <span style="color:green;font-weight:bold">Online</span><br>

    <?php if (isset($instance['show_host']) && $instance['show_host'] == 'on'): ?>
        Host: <strong><?php echo $server['server']['host']; ?></strong><br>
    <?php endif; ?>
